### ISSUE TITLE
Context Menu was removed. Not possible to add markers using right click any more

### ISSUE THREAD

**Issue by hollburg** [route360/r360-demo#17]

**Comment by gerbsen** [comment]
What exactly do you mean? I have this menu:

![screenshot 2016-07-15 09 54 33](https://cloud.githubusercontent.com/assets/1186245/16867446/2f97f4ea-4a72-11e6-8c2c-673f5d2790a2.png)

**Comment by gerbsen** [comment]
Ah, Cache issue.. @j-slvr could you tell me what's the problem and I'll fix this asap.

**Comment by hollburg** [comment]
![rightclick](https://cloud.githubusercontent.com/assets/8027727/16867545/b5a0d75a-4a72-11e6-9311-d64c026a6f11.jpg)

right click on chrome/windows
